### ISSUE TITLE
Build errors in Unity

### ISSUE THREAD

**Issue by yasuaki-kan** [microsoft/MixedReality-SceneUnderstanding-Samples#11]
Hi.

I'm having problems with the build of this project.
I'm not familiar with Unity, so I might be asking a rudimentary question.

**Build Environment**
 - Unity2019.4.19f1
 - Visual Studio Community 2019 16.8.5
 - MixedReality-SceneUnderstanding-Samples main branch

**Problem**
Multiple errors occur in SceneUnderstandingManager.cs
Line 571.
System.Numerics.Matrix4x4 converted4x4LocationMatrix = ConvertRightHandedMatrix4x4ToLeftHanded(suObject.GetLocationAsMatrix());
error CS7069: Reference to type 'Matrix4x4' claims it is defined in 'System.Numerics', but it could not be found

Similar errors have occurred in 11 places.

How can I prevent the error from occurring?

**Comment by satkowski** [comment]
We encountered the same issue since yesterday and would be happy if you had an idea how to solve this.
We use Unity 2019.4.22f.

**Comment by jorgonz** [comment]
We recently made some changes to how we build our project.

Primarily we removed Nuget For Unity, are you having this issue on a clean clone? or after a pull?

**Comment by jorgonz** [comment]
Can you also let me know if the problem persists with a clean clone of this branch?

https://github.com/microsoft/MixedReality-SceneUnderstanding-Samples/tree/LegacyNugetBuild

I want to know if this is a symptom of changing the way we pull packages now.

**Comment by yasuaki-kan** [comment]
Hi.

Thank you for checking.
No error occurred on line 571.
![1](https://user-images.githubusercontent.com/77378149/111815157-b003df00-891e-11eb-912c-ecfad0f67c8f.PNG)

However, it seems that there are some errors on another line.
I can't count all because there are so many errors, but I captured only one.
![2](https://user-images.githubusercontent.com/77378149/111815405-f8230180-891e-11eb-9bf1-663e8aeb4f56.PNG)

Please let me know if you have any other research.

**Comment by jorgonz** [comment]
Ok, you seem to have fixed the Numerics.Matrix 4x4 reference but know your project complains that its missing the SceneUnderstanding stuff.

Is this still 'Main' branch? can you take a look at your package Manager and tell me what you see?

Window -> PackageManager

**Comment by yasuaki-kan** [comment]
No, this is the "Legacy Nuget Build" branch.

![1](https://user-images.githubusercontent.com/77378149/111816660-6e743380-8920-11eb-87b4-b2898f871283.PNG)

![2](https://user-images.githubusercontent.com/77378149/111816777-96fc2d80-8920-11eb-9cf1-4f7325793246.PNG)

**Comment by jorgonz** [comment]
Ok ok, then go to the Nuget Window and make sure you have SceneUnderstanding as a Nuget Package

**Comment by yasuaki-kan** [comment]
It seems that SceneUnderstanding is not installed.
Should I install it?
![1](https://user-images.githubusercontent.com/77378149/111817333-3caf9c80-8921-11eb-8773-84589617c9ae.PNG)

**Comment by jorgonz** [comment]
Yes, try installing it

**Comment by yasuaki-kan** [comment]
An error occurs when I click Install.

Unable to retrieve package list from http://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.MixedReality.SceneUnderstanding'&$orderby=Version asc&$filter=Version eq '0.5.2069'
System.Net.WebException: The remote server returned an error: (400) Bad Request.

Could not find Microsoft.MixedReality.SceneUnderstanding 0.5.2069 or greater.

**Comment by jorgonz** [comment]
I'm looking into it, i think best fix here is to investigate what's happening in the main branch.

I'll swing back with an answer, sit tight!

**Comment by yasuaki-kan** [comment]
OK.
Thank you for your support.
I hope it can be solved successfully.

**Comment by jorgonz** [comment]
If you go back to your Project in Main Branch, the one with the original error.

what do you see here when you open Visual Studio? Can you Select 'Assembly-CSharp'
<img width="948" alt="Screenshot 2021-03-19 103805" src="https://user-images.githubusercontent.com/63747813/111820861-3973cc80-889f-11eb-9408-a5be318b21be.png">

Make sure Project is Setup to build as UWP
![image](https://user-images.githubusercontent.com/63747813/111820954-56100480-889f-11eb-9828-efe0fa5a750e.png)

does this fix the compilation issue for you?

**Comment by yasuaki-kan** [comment]
'Assembly-CSharp' exists, but'Assembly-CSharp'.Player' does not exist.
![1](https://user-images.githubusercontent.com/77378149/111822386-155bce00-8927-11eb-84a3-c110af51c49d.PNG)

And I switched the platform, but the error doesn't go away.
![2](https://user-images.githubusercontent.com/77378149/111822504-33c1c980-8927-11eb-9898-a7fbfc93e159.PNG)

**Comment by yasuaki-kan** [comment]
Hi.

Could you tell us about the current status?
Is there anything I can help you with?

**Comment by jorgonz** [comment]
It's difficult for me to triage because i cannot reproduce the conditions of your project, but you can try these things:

try regenerating the Visual Studio Files, with and without the Player Flag, Edit -> Preferences
![image](https://user-images.githubusercontent.com/63747813/112025211-30c70480-8af2-11eb-8da8-de37a33cec81.png)


You can also try deleting and redownloading the Scene Understanding Package in Window -> Package Mananger
![image](https://user-images.githubusercontent.com/63747813/112025467-6d92fb80-8af2-11eb-9067-0b266533054a.png)

**Comment by yasuaki-kan** [comment]
Thank you for your reply.

As a result of various trials, the error has been resolved, so I will report it.

I changed the version of Unity Editor from 2019.4.19f1 to 2019.4.11f.
And the problem was solved.

I hope this information helps everyone.

**Comment by jorgonz** [comment]
i see, i wouldn't have expected that a minor change such as the patch version (the last digits in the Unity version) would fix it, but I'm glad you were able to figure it out.

I think it would be smart to setup a 'Common Issues' section in the README and start gathering all the issues people see.

Thank you very much, i'll mark the issue as closed.

**Comment by rolandsmeenk** [comment]
Just ran into this, with Unity 2019.4.20f1 and 2019.4.16f1, but not with 2019.4.10f1  
Turns out that due to project upgrade the Api Compatibility Level fell back to .NET Standard 2.0.

Switch it to .Net 4.x to fix.
Build Settings > Player Settings > Other Settings > Api Compatibility Level > .Net 4.x

**Comment by tobias-tengler** [comment]
@rolandsmeenk This was also the issue in my case. Thanks for sharing the solution! :)
