### ISSUE TITLE
XR SDK pipeline

### ISSUE THREAD

**Issue by yasuaki-kan** [microsoft/MixedReality-SceneUnderstanding-Samples#12]
Hi,

Is it possible to run this project on the XR SDK pipeline instead of the Legacy XR pipeline?

I tried referring to the following, but I couldn't.
https://docs.microsoft.com/ja-jp/windows/mixed-reality/mrtk-unity/features/spatial-awareness/scene-understanding

If possible, please tell me how to implement it.

regards.

**Comment by jorgonz** [comment]
There are two ways in which you can consume SU now.

We worked with the MRTK team to allow users to opt in into SU from their Platform (MRTK), however its important to distinguish between different ways you can consume SU now

You can opt in Into MRTK, and import all of the MRTK tools, and then opt in into their experimental observer called SU, they have really good documentation about it.

https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/release-notes/mrtk-26-release-notes#scene-understanding-now-available-in-mrtk-as-an-experimental-spatial-awareness-observer

I'm not sure what XR pipeline they use.

Now if you grab our UPM package either manually in your project or download the sample you are grabbing SU and only SU, without MRTK.

it is 100% possible to run SU with the new XR pipeline, i just haven't had the time to actually do the change, hopefully its something i can get to do at some point with our next batch of changes.

If this is something you want to do in your personal branch or experiment with, follow the Unity documentation to remove the legacy XR pipeline and install the new one


very likely you will need to change the Cameras in the scene to use their new XR Rig 
![image](https://user-images.githubusercontent.com/63747813/113178622-9eb2b080-9203-11eb-9c33-be65449c3d18.png)

and change the way the we align spatial coordinate system to the unity space 
![image](https://user-images.githubusercontent.com/63747813/113178755-bc801580-9203-11eb-9465-073aec2e48c4.png)
https://github.com/microsoft/MixedReality-SceneUnderstanding-Samples/blob/user/jorgonz/dev/Assets/SceneUnderstanding/Core/Understanding/Scripts/SceneUnderstandingManager.cs#L1066

**Comment by jorgonz** [comment]
Ideally this is something that would be in our Main branch already, hopefully we will have time in the near future to update our sample with this and also a bunch of Quality of Life changes

**Comment by jorgonz** [comment]
Done with https://github.com/microsoft/MixedReality-SceneUnderstanding-Samples/pull/21

We are running in Unity 2020 with the Windows XR pipeline.
