### ISSUE TITLE
issue:The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by RenSiyao** [microsoft/MixedReality-SceneUnderstanding-Samples#13]
I tried to pull the project and open it with Unity2019.4.3, but this error occurred (the type or namespace name "Windows" could not be found). What should I do?

**Comment by RenSiyao** [comment]
The script reported an error inside Unity（SceneUnderstandingManager）

**Comment by jorgonz** [comment]
Hi @RenSiyao my guess is that perhaps you are missing the Windows SDK

https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk/

Can you provide a copy of your project/ screenshots, so that i can take a look at?

**Comment by RenSiyao** [comment]
> 嗨@RenSiyao我的猜测是，也许您缺少Windows SDK
> 
> [https://developer.microsoft.com/zh-CN/windows/downloads/windows-10-sdk/](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk/)
> 
> 您可以提供您的项目/屏幕截图的副本，以便我看看吗？

![image](https://user-images.githubusercontent.com/53859046/90354810-f3daf100-e07c-11ea-9814-65ae6dafcc22.png)
![image](https://user-images.githubusercontent.com/53859046/90354848-0c4b0b80-e07d-11ea-8729-75c711a912ce.png)

Here are my Unity screenshots and VS screenshots

**Comment by SzymonSPS** [comment]
Did you resolve this issue? You need to make sure you are using a supported OS version (19041) 

https://docs.microsoft.com/en-us/uwp/api/Windows.Perception.Spatial?view=winrt-19041

And an updated SDK. Looks like you have the right SDK. Can you try and build a standalone UWP project that references Windows.Perception.Spatial?
