### ISSUE TITLE
Can the 3D map can be converted to 2d and update dynamically?

### ISSUE THREAD

**Issue by jtrinidad6** [microsoft/MixedReality-SceneUnderstanding-Samples#18]
Hello,

I have a question and maybe you can give me some insights about what I want to achieve.

I have the sample Scene Understanding SDK running and it can perfectly generate the 3d map based on the scanned areas of a room. I was wondering of that map can be 2d instead? like, show the position of the hololens inside the 2d map? 

P.S I am new to unity and hololens and trying to learn something.

Thanks.

**Comment by SzymonSPS** [comment]
It can! We have a sample we're writing that converts SU data to 2D maps but it's not ready yet. The high level idea is to find the floor and project the walls on the floor in 2D. We do want to share it but it may be a while, but we can help share some of the key code beforehand.

**Comment by jtrinidad6** [comment]
Right now, I am using spatial mapping and applying some shader to distinguish walls, floors, and obstacles. But I am not having some great results in the hololens. That is why I thought of using SU SDK because it automatically creates the 3d map and trying to figure out how to get it in 2d.

If you could share some of the code that would be awesome.

**Comment by SzymonSPS** [comment]
Let me share some snippets of code to see if these help. Warning, these come

Find a floor:

        SceneObject FindLargestFloor(Scene scene)
        {
            var floors = scene.SceneObjects.Where<SceneObject>(x => (x.Kind == SceneObjectKind.Floor)).ToArray();
            float areaForLrgestFloorSoFar = 0;
            SceneObject largestFloor = null;

            foreach (var so in floors)
            {
                // Look at quad areas
                if (so.Quads.Count > 0)
                {
                    var quad = so.Quads[0];
                    var area = quad.Extents.X * quad.Extents.Y;
                    if (area > areaForLrgestFloorSoFar)
                    {
                        areaForLrgestFloorSoFar = area;
                        largestFloor = so;
                    }
                }
            }
            return largestFloor;
        }

Find the transform that maps walls to"floor space"

 var largestFloor = FindLargestFloor(_myScene);

            // No floor, we're done, nothing to see here
            if (largestFloor == null)
            {
                return floorPlan;
            }

            // Find the inverse floor transform which will rotate everything to be floor up
            var inverseFloorTransform = largestFloor.GetLocationAsMatrix();
            Matrix4x4.Invert(inverseFloorTransform, out inverseFloorTransform);

            // Find all of the walls on the  floor
            var walls = Find2DWalls(_myScene, floors.ToArray(), inverseFloorTransform);

Code that projects walls to the floor:

        void FindAndAddAllWalls(Scene scene, Floor[] floorsSortedByOffset, Matrix4x4 inverseFloorTransform)
        {
            var wallSceneObjects = scene.SceneObjects.Where<SceneObject>(x => (x.Kind == SceneObjectKind.Wall)).ToArray();

            foreach (var wallSceneObject in wallSceneObjects)
            {
                // Transform the plane to it's location, and then align it with the largest floor
                var transformedWallPoints = new List<Vector3>();

                var transformToFloorUpSpace = wallSceneObject.GetLocationAsMatrix() * inverseFloorTransform;

                foreach (var mesh in wallSceneObject.Meshes)
                {
                    // Get all vertices
                    var positions = new Vector3[mesh.VertexCount];
                    mesh.GetVertexPositions(positions);

                    // Transform them
                    for (int i = 0; i < positions.Length; i++)
                    {
                        positions[i] = Vector3.Transform(positions[i], transformToFloorUpSpace);
                    }

                    // Add them to the list
                    transformedWallPoints.AddRange(positions);
                }

                var wallToAdd = new Wall();
                if (GetWallDataIfValid(transformedWallPoints.ToArray(), ref wallToAdd))
                {
                    // Where should we add this wall
                    for (int i = 0; i < floorsSortedByOffset.Length; i++)
                    {
                        // If this is the last floor, add it here
                        if ((i == floorsSortedByOffset.Length - 1) || (wallToAdd.offset > (floorsSortedByOffset[i].offset - _floorOffsetEpsilon) && wallToAdd.offset < (floorsSortedByOffset[i + 1].offset - _floorOffsetEpsilon)))
                        {
                            wallToAdd.offset -= floorsSortedByOffset[i].offset;

                            if (Math.Abs(wallToAdd.offset) < 0.2f)
                            {
                                floorsSortedByOffset[i].walls.Add(wallToAdd);
                            }
                            break;
                        }
                    }
                }
            }
        }

This code references some more complicated multi-floor structures, so again it won't "just work" but it should give you an idea of how to get started. To know where your device is relative to the floor, you would transform it the same way you transform the wall, multiply by the inverse floor transform. Let us know how things go, we do want to release this code but it's just not ready yet.
