### ISSUE TITLE
Errors occur when adding the project to Unity

### ISSUE THREAD

**Issue by m-kazuya** [microsoft/MixedReality-SceneUnderstanding-Samples#19]
Hi, 

 I have the following two problems when adding this project to Unity 2019 2.12f

----
1. PrecompiledAssemblyException: Multiple precompiled assemblies with the same name Microsoft.MixedReality.SceneUnderstanding.DotNet.dll included for the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: Assets/Packages/Microsoft.MixedReality.SceneUnderstanding.0.5.2069/lib/netstandard1.3/Microsoft.MixedReality.SceneUnderstanding.DotNet.dll, Assets/Packages/Microsoft.MixedReality.SceneUnderstanding.0.5.2069/lib/netstandard2.0/Microsoft.MixedReality.SceneUnderstanding.DotNet.dll, Assets/Packages/Microsoft.MixedReality.SceneUnderstanding.0.5.2069/lib/uap10.0.18362/Microsoft.MixedReality.SceneUnderstanding.DotNet.dll, Assets/Packages/Microsoft.MixedReality.SceneUnderstanding.0.5.2069/lib/unity/net46/Microsoft.MixedReality.SceneUnderstanding.DotNet.dll

2. Assets\SceneUnderstanding\Examples\StandardAssets\Scripts\ActionMenuItem.cs(3,7): error CS0246: The type or namespace name 'TMPro' could not be found (are you missing a using directive or an assembly reference?)
------
I'd be happy to get some advice.

Best regards

**Comment by m-kazuya** [comment]
Thank you for your reply!

Q: Did you start your project straight out of our sample code
A: Yes. I started the project by adding MixedReality-SceneUnderstanding-Samples-master folder to Unity.

Q: are you trying to integrate Scene Understanding into an already existing project.
A: No

Q: Are you using Nuget for Unity?
A: Yes. I use Nuget ver.2.0.0.

**Comment by jorgonz** [comment]
It sounds to me like it might be an issue with Nuget For Unity not initializing properly.

how did you copied the MixedReality-SceneUnderstanding-Samples into your own computer?

was it a 'git clone' command?

e.g 

![image](https://user-images.githubusercontent.com/63747813/96627610-f993c380-12c5-11eb-8b11-3f86b4086f20.png)

**Comment by m-kazuya** [comment]
The problems have been vanished by copying the samples by git clone.
Thank you for your kind help!!
