### ISSUE TITLE
[Question] Mesh Resolution

### ISSUE THREAD

**Issue by lekhachoa** [microsoft/MixedReality-SceneUnderstanding-Samples#29]
Hello, 
I'm quite new to MRTK Hololens. I was navigated to use Scene Understanding to get higher mesh resolution (https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/10354#discussioncomment-1761348)
So, what is the highest resolution could I get from SceneUnderstanding? Could it reach 1cm resolution? Could I use Hololens 2 to get 3D Object by scanning an object e.g a small machine, machine part in multiple times (to get a dense point cloud, which is supposed to provide more detail for mesh generation)?

**Comment by SzymonSPS** [comment]
Hello, yes, the Scene Understanding SDK will give you access to the highest mesh resolution possible.

When making a request using SceneQuerySettings and setting

RequestedMeshLevelOfDetail to Unlimited

This basically says, send the highest resolution you can, regardless of size. 

To answer your specific questions on size, this is the highest resolution spatial map, but it is still limited to what the device scans in real time. 1cm resolution is a hard thing to answer as the runtime can detail like this in some areas, but at it's core there is a resolution of 4cm that has to do with the smallest gap between two surfaces or size of objects. Small machines could work, but I think you should try it as it's really hard for me to tell how big and detailed it is.
