### ISSUE TITLE
Do we intend to use combinedMeshVertices.Count rather than combinedMeshIndices.Count when stitching meshes?

### ISSUE THREAD

**Issue by darax** [microsoft/MixedReality-SceneUnderstanding-Samples#8]
https://github.com/microsoft/MixedReality-SceneUnderstanding-Samples/blob/d64b61c0644aa1de091223c8f2b68754d91e22db/Assets/SceneUnderstanding/Core/Understanding/Scripts/SceneUnderstandingManager.cs#L752

**Comment by darax** [comment]
So far my scenes have only had one mesh, so nothing is being combined. I suspect if there were multiple meshes being combined the results would not be the intended mesh.

**Comment by SzymonSPS** [comment]
If you request world meshes with a high enough resolution there can be more than one mesh that is returned as they exceed volume/size limits. This does look like a bug however, we will test and look into it.

**Comment by jorgonz** [comment]
This was indeed a bug.

it's fixed now 

https://github.com/microsoft/MixedReality-SceneUnderstanding-Samples/commit/5582756362fcba7179dd6bf3eabb6b2b25414539
