### ISSUE TITLE
Is suMesh intended here instead of suMeshes?

### ISSUE THREAD

**Issue by darax** [microsoft/MixedReality-SceneUnderstanding-Samples#9]
https://github.com/microsoft/MixedReality-SceneUnderstanding-Samples/blob/5582756362fcba7179dd6bf3eabb6b2b25414539/Assets/SceneUnderstanding/Core/Understanding/Scripts/SceneUnderstandingManager.cs#L740

**Comment by jorgonz** [comment]
It was indeed a typo, thanks for catching it!

it's fixed now
https://github.com/microsoft/MixedReality-SceneUnderstanding-Samples/commit/b90e9230629ed566d5f96dc1d98ff964914dcbb0
